<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>
<!DOCTYPE stationlist [
<!ELEMENT stationlist (station+)>
<!ATTLIST stationlist
  created	CDATA	#REQUIRED
>

<!ELEMENT station (comp+)>
<!ATTLIST station
  code		CDATA 			#REQUIRED
  name		CDATA 			#REQUIRED
  insttype	CDATA 			#REQUIRED
  lat		CDATA 			#REQUIRED
  lon		CDATA 			#REQUIRED
  source	(SCSN|CGS|NSMP) 	'SCSN'
  commtype	(DIG|ANA) 		'DIG'
  dist          CDATA                   '10.0'
  loc		CDATA			''
>

<!ELEMENT comp (acc,vel,psa*)>
<!ATTLIST comp
  name          CDATA  #REQUIRED
  originalname  CDATA  #IMPLIED
>

<!ELEMENT acc EMPTY>
<!ELEMENT vel EMPTY>
<!ELEMENT psa03 EMPTY>
<!ELEMENT psa10 EMPTY>
<!ELEMENT psa30 EMPTY>
<!ATTLIST acc
  value  CDATA         #REQUIRED
  flag   CDATA        ''
>
<!ATTLIST vel
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa03
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa10
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa30
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
]>
<stationlist created="1584874117">
<station code="AGR" name="Agrigento" insttype="UNR" lat="37.3231" lon="13.5860" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00244340" flag="0" />
<vel value="0.00033800" flag="0" />
<psa10 value="0.00052153" flag="0" />
<psa30 value="0.00002565" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00238167" flag="0" />
<vel value="0.00058500" flag="0" />
<psa10 value="0.00101137" flag="0" />
<psa30 value="0.00004783" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00226956" flag="0" />
<vel value="0.00043200" flag="0" />
<psa10 value="0.00069547" flag="0" />
<psa30 value="0.00003802" flag="0" />
</comp>
</station>
<station code="BNT" name="Bronte" insttype="UNR" lat="37.7805" lon="14.8444" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.05507170" flag="0" />
<vel value="0.03190400" flag="0" />
<psa03 value="0.14929846" flag="0" />
<psa10 value="0.02590688" flag="0" />
<psa30 value="0.00127760" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.04821857" flag="0" />
<vel value="0.02468100" flag="0" />
<psa03 value="0.11784294" flag="0" />
<psa10 value="0.01486346" flag="0" />
<psa30 value="0.00124480" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.02770938" flag="0" />
<vel value="0.01324200" flag="0" />
<psa03 value="0.05980887" flag="0" />
<psa10 value="0.02208368" flag="0" />
<psa30 value="0.00109385" flag="0" />
</comp>
</station>
<station code="BVM" name="Bova Marina" insttype="UNR" lat="37.9310" lon="15.9360" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00155272" flag="0" />
<vel value="0.00070600" flag="0" />
<psa10 value="0.00084366" flag="0" />
<psa30 value="0.00004211" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00153954" flag="0" />
<vel value="0.00067700" flag="0" />
<psa10 value="0.00077897" flag="0" />
<psa30 value="0.00003291" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00106400" flag="0" />
<vel value="0.00041800" flag="0" />
<psa10 value="0.00058039" flag="0" />
<psa30 value="0.00001921" flag="0" />
</comp>
</station>
<station code="CAT" name="Catania_Piana" insttype="UNR" lat="37.4473" lon="15.0463" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HGE">
<acc value="0.04587625" flag="0" />
<vel value="0.01717800" flag="0" />
<psa10 value="0.01398556" flag="0" />
<psa30 value="0.00068392" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="0.03156549" flag="0" />
<vel value="0.00856900" flag="0" />
<psa10 value="0.01081879" flag="0" />
<psa30 value="0.00059593" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.02874293" flag="0" />
<vel value="0.00552300" flag="0" />
<psa10 value="0.00558114" flag="0" />
<psa30 value="0.00033501" flag="0" />
</comp>
</station>
<station code="CDI1" name="Castel di Iudica" insttype="UNR" lat="37.5032" lon="14.6473" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00594548" flag="0" />
<vel value="0.00182600" flag="0" />
<psa10 value="0.00166933" flag="0" />
<psa30 value="0.00006909" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.01104884" flag="0" />
<vel value="0.00546400" flag="0" />
<psa10 value="0.00232229" flag="0" />
<psa30 value="0.00020624" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00306242" flag="0" />
<vel value="0.00146700" flag="0" />
<psa10 value="0.00122528" flag="0" />
<psa30 value="0.00006561" flag="0" />
</comp>
</station>
<station code="CFL" name="Cefalu" insttype="UNR" lat="38.0370" lon="14.0232" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00046756" flag="0" />
<vel value="0.00029300" flag="0" />
<psa10 value="0.00063252" flag="0" />
<psa30 value="0.00001809" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00062301" flag="0" />
<vel value="0.00049100" flag="0" />
<psa10 value="0.00101127" flag="0" />
<psa30 value="0.00002759" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00051172" flag="0" />
<vel value="0.00028200" flag="0" />
<psa10 value="0.00042229" flag="0" />
<psa30 value="0.00001502" flag="0" />
</comp>
</station>
<station code="CLG1" name="Caltagirone" insttype="UNR" lat="37.2214" lon="14.5182" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00492124" flag="0" />
<vel value="0.00167800" flag="0" />
<psa10 value="0.00163408" flag="0" />
<psa30 value="0.00008002" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00444764" flag="0" />
<vel value="0.00125300" flag="0" />
<psa10 value="0.00167935" flag="0" />
<psa30 value="0.00007164" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00340316" flag="0" />
<vel value="0.00085400" flag="0" />
<psa10 value="0.00088147" flag="0" />
<psa30 value="0.00004078" flag="0" />
</comp>
</station>
<station code="CON" name="Corleone" insttype="UNR" lat="37.8138" lon="13.3080" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HGE">
<acc value="0.00042147" flag="0" />
<vel value="0.00035800" flag="0" />
<psa10 value="0.00094188" flag="0" />
<psa30 value="0.00003536" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="0.00034625" flag="0" />
<vel value="0.00025600" flag="0" />
<psa10 value="0.00061371" flag="0" />
<psa30 value="0.00001911" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.00040073" flag="0" />
<vel value="0.00025100" flag="0" />
<psa10 value="0.00046675" flag="0" />
<psa30 value="0.00002064" flag="0" />
</comp>
</station>
<station code="CSM" name="Casteltermini" insttype="UNR" lat="37.5404" lon="13.6273" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HGE">
<acc value="0.00715339" flag="0" />
<vel value="0.00076000" flag="0" />
<psa10 value="0.00064478" flag="0" />
<psa30 value="0.00002821" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="0.00754124" flag="0" />
<vel value="0.00077000" flag="0" />
<psa10 value="0.00071571" flag="0" />
<psa30 value="0.00002913" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.00206689" flag="0" />
<vel value="0.00024900" flag="0" />
<psa10 value="0.00040768" flag="0" />
<psa30 value="0.00001329" flag="0" />
</comp>
</station>
<station code="CTU" name="Caltavuturo" insttype="UNR" lat="37.8232" lon="13.8904" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00085000" flag="0" />
<vel value="0.00048500" flag="0" />
<psa10 value="0.00105092" flag="0" />
<psa30 value="0.00002923" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00100258" flag="0" />
<vel value="0.00066800" flag="0" />
<psa10 value="0.00114229" flag="0" />
<psa30 value="0.00003832" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00058029" flag="0" />
<vel value="0.00043500" flag="0" />
<psa10 value="0.00065388" flag="0" />
<psa30 value="0.00002340" flag="0" />
</comp>
</station>
<station code="CTV" name="Cittanova" insttype="UNR" lat="38.3498" lon="16.0804" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00518522" flag="0" />
<vel value="0.00091400" flag="0" />
<psa10 value="0.00107852" flag="0" />
<psa30 value="0.00004108" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00518471" flag="0" />
<vel value="0.00056700" flag="0" />
<psa10 value="0.00086574" flag="0" />
<psa30 value="0.00002872" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00637329" flag="0" />
<vel value="0.00045500" flag="0" />
<psa10 value="0.00063619" flag="0" />
<psa30 value="0.00002054" flag="0" />
</comp>
</station>
<station code="GBL" name="Gibellina Santa Ninfa" insttype="UNR" lat="37.7961" lon="12.9142" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00208876" flag="0" />
<vel value="0.00038200" flag="0" />
<psa30 value="0.00001513" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00168875" flag="0" />
<vel value="0.00044100" flag="0" />
<psa30 value="0.00001829" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00083242" flag="0" />
<vel value="0.00024800" flag="0" />
<psa30 value="0.00001002" flag="0" />
</comp>
</station>
<station code="GSM" name="Gioiosa Marea" insttype="UNR" lat="38.1720" lon="14.8985" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00492829" flag="0" />
<vel value="0.00230800" flag="0" />
<psa30 value="0.00008462" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00324383" flag="0" />
<vel value="0.00134800" flag="0" />
<psa30 value="0.00005621" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00259353" flag="0" />
<vel value="0.00169700" flag="0" />
<psa30 value="0.00006081" flag="0" />
</comp>
</station>
<station code="LMZ" name="Lamezia Terme" insttype="UNR" lat="38.9187" lon="16.2527" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00301715" flag="0" />
<vel value="0.00067300" flag="0" />
<psa10 value="0.00063722" flag="0" />
<psa30 value="0.00003025" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00386183" flag="0" />
<vel value="0.00051200" flag="0" />
<psa10 value="0.00057825" flag="0" />
<psa30 value="0.00002361" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00296676" flag="0" />
<vel value="0.00037000" flag="0" />
<psa10 value="0.00037191" flag="0" />
<psa30 value="0.00001523" flag="0" />
</comp>
</station>
<station code="LNT" name="Lentini" insttype="UNR" lat="37.2884" lon="15.0022" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HGE">
<acc value="0.00782218" flag="0" />
<vel value="0.00365600" flag="0" />
<psa10 value="0.00148548" flag="0" />
<psa30 value="0.00013715" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="0.00789311" flag="0" />
<vel value="0.00289900" flag="0" />
<psa10 value="0.00163295" flag="0" />
<psa30 value="0.00009985" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.00652322" flag="0" />
<vel value="0.00124800" flag="0" />
<psa10 value="0.00080503" flag="0" />
<psa30 value="0.00006030" flag="0" />
</comp>
</station>
<station code="LPR1" name="Lipari" insttype="UNR" lat="38.4695" lon="14.9569" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.01084117" flag="0" />
<vel value="0.00126300" flag="0" />
<psa10 value="0.00154700" flag="0" />
<psa30 value="0.00005539" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.01330000" flag="0" />
<vel value="0.00147200" flag="0" />
<psa10 value="0.00256563" flag="0" />
<psa30 value="0.00008994" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.01383430" flag="0" />
<vel value="0.00120700" flag="0" />
<psa10 value="0.00074708" flag="0" />
<psa30 value="0.00003700" flag="0" />
</comp>
</station>
<station code="MFG" name="Messina Forte Gonzaga" insttype="UNR" lat="38.1888" lon="15.5406" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00470457" flag="0" />
<vel value="0.00241600" flag="0" />
<psa10 value="0.00196030" flag="0" />
<psa30 value="0.00009270" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00443517" flag="0" />
<vel value="0.00207200" flag="0" />
<psa10 value="0.00145758" flag="0" />
<psa30 value="0.00009515" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00318752" flag="0" />
<vel value="0.00144000" flag="0" />
<psa10 value="0.00092511" flag="0" />
<psa30 value="0.00005018" flag="0" />
</comp>
</station>
<station code="MZZ" name="Milazzo" insttype="UNR" lat="38.2341" lon="15.2451" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00469343" flag="0" />
<vel value="0.00128400" flag="0" />
<psa10 value="0.00134311" flag="0" />
<psa30 value="0.00006459" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00452133" flag="0" />
<vel value="0.00163700" flag="0" />
<psa10 value="0.00126524" flag="0" />
<psa30 value="0.00006919" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00392244" flag="0" />
<vel value="0.00109700" flag="0" />
<psa10 value="0.00082588" flag="0" />
<psa30 value="0.00005417" flag="0" />
</comp>
</station>
<station code="NSA" name="Nicosia" insttype="UNR" lat="37.7667" lon="14.4110" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00322216" flag="0" />
<vel value="0.00285600" flag="0" />
<psa03 value="0.00926474" flag="0" />
<psa10 value="0.00508568" flag="0" />
<psa30 value="0.00046613" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00311444" flag="0" />
<vel value="0.00333000" flag="0" />
<psa03 value="0.00975468" flag="0" />
<psa10 value="0.00522252" flag="0" />
<psa30 value="0.00047625" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00204053" flag="0" />
<vel value="0.00162500" flag="0" />
<psa03 value="0.00694521" flag="0" />
<psa10 value="0.00323126" flag="0" />
<psa30 value="0.00057232" flag="0" />
</comp>
</station>
<station code="NVR1" name="Novara di Sicilia" insttype="UNR" lat="38.0124" lon="15.1288" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.02100343" flag="0" />
<vel value="0.00945200" flag="0" />
<psa10 value="0.01137731" flag="0" />
<psa30 value="0.00051202" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.02842131" flag="0" />
<vel value="0.01551400" flag="0" />
<psa10 value="0.00654039" flag="0" />
<psa30 value="0.00052398" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.02063162" flag="0" />
<vel value="0.00424600" flag="0" />
<psa10 value="0.00441514" flag="0" />
<psa30 value="0.00021513" flag="0" />
</comp>
</station>
<station code="PLR" name="Palermo" insttype="UNR" lat="38.1509" lon="13.3425" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00714398" flag="0" />
<vel value="0.00040500" flag="0" />
<psa10 value="0.00067759" flag="0" />
<psa30 value="0.00002228" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00813543" flag="0" />
<vel value="0.00048700" flag="0" />
<psa10 value="0.00107341" flag="0" />
<psa30 value="0.00002299" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00823180" flag="0" />
<vel value="0.00060000" flag="0" />
<psa10 value="0.00065950" flag="0" />
<psa30 value="0.00002555" flag="0" />
</comp>
</station>
<station code="PLZ" name="Palazzolo Acreide" insttype="UNR" lat="37.0682" lon="14.9097" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00864469" flag="0" />
<vel value="0.00181300" flag="0" />
<psa10 value="0.00094085" flag="0" />
<psa30 value="0.00005693" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.01168463" flag="0" />
<vel value="0.00224700" flag="0" />
<psa10 value="0.00112737" flag="0" />
<psa30 value="0.00007685" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00488771" flag="0" />
<vel value="0.00162900" flag="0" />
<psa10 value="0.00066502" flag="0" />
<psa30 value="0.00004221" flag="0" />
</comp>
</station>
<station code="PTR" name="Paterno" insttype="UNR" lat="37.5620" lon="14.9077" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HGE">
<acc value="0.03222693" flag="0" />
<vel value="0.01305300" flag="0" />
<psa10 value="0.01615537" flag="0" />
<psa30 value="0.00137674" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="0.02635626" flag="0" />
<vel value="0.00758600" flag="0" />
<psa10 value="0.00785387" flag="0" />
<psa30 value="0.00055055" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.02223453" flag="0" />
<vel value="0.00804100" flag="0" />
<psa10 value="0.01601331" flag="0" />
<psa30 value="0.00059388" flag="0" />
</comp>
</station>
<station code="RCU" name="Reggio_Calabria_Universita" insttype="UNR" lat="38.1214" lon="15.6662" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HGE">
<acc value="0.00179760" flag="0" />
<vel value="0.00075200" flag="0" />
<psa10 value="0.00078970" flag="0" />
<psa30 value="0.00003608" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="0.00160413" flag="0" />
<vel value="0.00079400" flag="0" />
<psa10 value="0.00103794" flag="0" />
<psa30 value="0.00003526" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.00108710" flag="0" />
<vel value="0.00052500" flag="0" />
<psa10 value="0.00061892" flag="0" />
<psa30 value="0.00002085" flag="0" />
</comp>
</station>
<station code="SCI" name="Scilla" insttype="UNR" lat="38.2557" lon="15.7147" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00153443" flag="0" />
<vel value="0.00097000" flag="0" />
<psa10 value="0.00068494" flag="0" />
<psa30 value="0.00003741" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00245260" flag="0" />
<vel value="0.00135700" flag="0" />
<psa10 value="0.00114239" flag="0" />
<psa30 value="0.00006132" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00117060" flag="0" />
<vel value="0.00038000" flag="0" />
<psa10 value="0.00034503" flag="0" />
<psa30 value="0.00001482" flag="0" />
</comp>
</station>
<station code="SCR" name="Santa Croce Camerina" insttype="UNR" lat="36.8296" lon="14.5275" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00436588" flag="0" />
<vel value="0.00117700" flag="0" />
<psa10 value="0.00079103" flag="0" />
<psa30 value="0.00004732" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00374328" flag="0" />
<vel value="0.00103700" flag="0" />
<psa10 value="0.00075894" flag="0" />
<psa30 value="0.00003577" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00280978" flag="0" />
<vel value="0.00061000" flag="0" />
<psa10 value="0.00040379" flag="0" />
<psa30 value="0.00002208" flag="0" />
</comp>
</station>
<station code="SRT" name="Sortino" insttype="UNR" lat="37.1665" lon="15.0542" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HGE">
<acc value="0.04111097" flag="0" />
<vel value="0.00723400" flag="0" />
<psa10 value="0.00211615" flag="0" />
<psa30 value="0.00021115" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="0.03455873" flag="0" />
<vel value="0.00606800" flag="0" />
<psa10 value="0.00208672" flag="0" />
<psa30 value="0.00019183" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.02267450" flag="0" />
<vel value="0.00289600" flag="0" />
<psa10 value="0.00087882" flag="0" />
<psa30 value="0.00007553" flag="0" />
</comp>
</station>
<station code="STC" name="Santo Stefano di Camastra" insttype="UNR" lat="38.0063" lon="14.3530" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00292547" flag="0" />
<vel value="0.00154700" flag="0" />
<psa10 value="0.00094198" flag="0" />
<psa30 value="0.00005028" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00356719" flag="0" />
<vel value="0.00162700" flag="0" />
<psa10 value="0.00180690" flag="0" />
<psa30 value="0.00008401" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00225167" flag="0" />
<vel value="0.00081500" flag="0" />
<psa10 value="0.00070477" flag="0" />
<psa30 value="0.00003413" flag="0" />
</comp>
</station>
<station code="SVN" name="Santa Venerina" insttype="UNR" lat="37.6830" lon="15.1299" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.66626428" flag="0" />
<vel value="0.19385100" flag="0" />
<psa03 value="1.10164415" flag="0" />
<psa10 value="0.06609785" flag="0" />
<psa30 value="0.00588478" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.79477128" flag="0" />
<vel value="0.22692100" flag="0" />
<psa03 value="1.00400299" flag="0" />
<psa10 value="0.05865054" flag="0" />
<psa30 value="0.00694265" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.54903669" flag="0" />
<vel value="0.13166800" flag="0" />
<psa03 value="0.55696241" flag="0" />
<psa10 value="0.02296873" flag="0" />
<psa30 value="0.00306017" flag="0" />
</comp>
</station>
<station code="TOR" name="Tortorici" insttype="UNR" lat="38.0443" lon="14.8146" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.01132734" flag="0" />
<vel value="0.00477900" flag="0" />
<psa10 value="0.00507965" flag="0" />
<psa30 value="0.00019929" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00772632" flag="0" />
<vel value="0.00404100" flag="0" />
<psa10 value="0.00465868" flag="0" />
<psa30 value="0.00022034" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00461872" flag="0" />
<vel value="0.00203600" flag="0" />
<psa10 value="0.00179606" flag="0" />
<psa30 value="0.00017200" flag="0" />
</comp>
</station>
<station code="VBM" name="Vibo Marina" insttype="UNR" lat="38.7138" lon="16.1238" netid="IT" source="Italian Strong Motion Network (RAN)" commtype="DIG">
<comp name="--.HNE">
<acc value="0.00339059" flag="0" />
<vel value="0.00062100" flag="0" />
<psa30 value="0.00002228" flag="0" />
</comp>
<comp name="--.HNN">
<acc value="0.00284760" flag="0" />
<vel value="0.00079200" flag="0" />
<psa30 value="0.00002514" flag="0" />
</comp>
<comp name="--.HNZ">
<acc value="0.00255347" flag="0" />
<vel value="0.00044200" flag="0" />
<psa30 value="0.00001461" flag="0" />
</comp>
</station>

</stationlist>
