<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>
<!DOCTYPE stationlist [
<!ELEMENT stationlist (station+)>
<!ATTLIST stationlist
  created	CDATA	#REQUIRED
>

<!ELEMENT station (comp+)>
<!ATTLIST station
  code		CDATA 			#REQUIRED
  name		CDATA 			#REQUIRED
  insttype	CDATA 			#REQUIRED
  lat		CDATA 			#REQUIRED
  lon		CDATA 			#REQUIRED
  source	(SCSN|CGS|NSMP) 	'SCSN'
  commtype	(DIG|ANA) 		'DIG'
  dist          CDATA                   '10.0'
  loc		CDATA			''
>

<!ELEMENT comp (acc,vel,psa*)>
<!ATTLIST comp
  name          CDATA  #REQUIRED
  originalname  CDATA  #IMPLIED
>

<!ELEMENT acc EMPTY>
<!ELEMENT vel EMPTY>
<!ELEMENT psa03 EMPTY>
<!ELEMENT psa10 EMPTY>
<!ELEMENT psa30 EMPTY>
<!ATTLIST acc
  value  CDATA         #REQUIRED
  flag   CDATA        ''
>
<!ATTLIST vel
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa03
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa10
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa30
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
]>
<stationlist created="1480506526">
<station code="0CAN" name="Cantiano Temporanea" insttype="UNR" lat="43.4723" lon="12.6308" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="1.84120004" flag="0" />
<vel value="0.73005800" flag="0" />
<psa03 value="4.68092955" flag="0" />
<psa10 value="0.62351198" flag="0" />
<psa30 value="0.21242147" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="1.41203772" flag="0" />
<vel value="0.81330700" flag="0" />
<psa03 value="2.82806930" flag="0" />
<psa10 value="0.77688209" flag="0" />
<psa30 value="0.20265330" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="1.18061491" flag="0" />
<vel value="0.74527500" flag="0" />
<psa03 value="2.78816286" flag="0" />
<psa10 value="0.77583004" flag="0" />
<psa30 value="0.21781906" flag="0" />
</comp>
</station>
<station code="0MBT" name="Citta_di_Castello_(Ospizio)" insttype="UNR" lat="43.4621" lon="12.2488" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="2.05274188" flag="0" />
<vel value="2.48499500" flag="0" />
<psa03 value="6.74531538" flag="0" />
<psa10 value="3.11999185" flag="0" />
<psa30 value="1.39841313" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="2.39581369" flag="0" />
<vel value="2.80098900" flag="0" />
<psa03 value="6.97988452" flag="0" />
<psa10 value="4.37471587" flag="0" />
<psa30 value="1.10631776" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="1.06721420" flag="0" />
<vel value="1.76852700" flag="0" />
<psa03 value="2.47167654" flag="0" />
<psa10 value="1.91676815" flag="0" />
<psa30 value="0.65821849" flag="0" />
</comp>
</station>
<station code="0PIO" name="Piobbico_Temporanea" insttype="UNR" lat="43.5873" lon="12.5127" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="1.33598385" flag="0" />
<vel value="0.86086500" flag="0" />
<psa03 value="2.78541767" flag="0" />
<psa10 value="0.85159632" flag="0" />
<psa30 value="0.17937970" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="1.52632869" flag="0" />
<vel value="0.59449000" flag="0" />
<psa03 value="3.59399566" flag="0" />
<psa10 value="0.49737357" flag="0" />
<psa30 value="0.14599485" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.87990398" flag="0" />
<vel value="0.60432900" flag="0" />
<psa03 value="3.04422363" flag="0" />
<psa10 value="0.60690417" flag="0" />
<psa30 value="0.22762331" flag="0" />
</comp>
</station>
<station code="0REN" name="Renzetti Temporanea" insttype="UNR" lat="43.5462" lon="12.2640" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="0.27716405" flag="0" />
<vel value="0.59114300" flag="0" />
<psa03 value="0.68350573" flag="0" />
<psa10 value="0.57099140" flag="0" />
<psa30 value="0.35276538" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="0.32357542" flag="0" />
<vel value="0.91888400" flag="0" />
<psa03 value="0.94458810" flag="0" />
<psa10 value="0.49887591" flag="0" />
<psa30 value="0.57728528" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.30350651" flag="0" />
<vel value="0.84199600" flag="0" />
<psa03 value="0.66429142" flag="0" />
<psa10 value="0.45510529" flag="0" />
<psa30 value="0.94287635" flag="0" />
</comp>
</station>
<station code="0UM8" name="Umbertide Temporanea" insttype="UNR" lat="43.3041" lon="12.3410" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="2.72996773" flag="0" />
<vel value="3.01050200" flag="0" />
<psa03 value="6.61557708" flag="0" />
<psa10 value="4.43370509" flag="0" />
<psa30 value="1.71394438" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="3.26415425" flag="0" />
<vel value="3.09279300" flag="0" />
<psa03 value="6.05329466" flag="0" />
<psa10 value="5.19903398" flag="0" />
<psa30 value="0.92847371" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="1.68149885" flag="0" />
<vel value="1.60257800" flag="0" />
<psa03 value="3.15278896" flag="0" />
<psa10 value="3.82851951" flag="0" />
<psa30 value="0.60728865" flag="0" />
</comp>
</station>
<station code="ACC" name="Accumoli" insttype="UNR" lat="42.6960" lon="13.2420" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="46.52319723" flag="0" />
<vel value="38.59933100" flag="0" />
<psa03 value="135.52901442" flag="0" />
<psa10 value="37.08220395" flag="0" />
<psa30 value="7.29103651" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="39.87389077" flag="0" />
<vel value="43.19803600" flag="0" />
<psa03 value="114.94431006" flag="0" />
<psa10 value="63.35976453" flag="0" />
<psa30 value="6.99771596" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="55.07923161" flag="0" />
<vel value="19.20808600" flag="0" />
<psa03 value="60.36682158" flag="0" />
<psa10 value="24.91933422" flag="0" />
<psa30 value="5.95847401" flag="0" />
</comp>
</station>
<station code="ACT" name="Acquasanta Terme" insttype="UNR" lat="42.7713" lon="13.4125" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="26.04973296" flag="0" />
<vel value="4.89021400" flag="0" />
<psa03 value="10.81305505" flag="0" />
<psa10 value="5.28396617" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="38.72409713" flag="0" />
<vel value="8.86951300" flag="0" />
<psa03 value="20.95518243" flag="0" />
<psa10 value="5.77062979" flag="0" />
<psa30 value="2.31801476" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="29.07874760" flag="0" />
<vel value="6.42981800" flag="0" />
<psa03 value="16.13671039" flag="0" />
<psa10 value="7.28378429" flag="0" />
<psa30 value="2.49585482" flag="0" />
</comp>
</station>
<station code="AMT" name="Amatrice" insttype="UNR" lat="42.6325" lon="13.2866" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="62.03594268" flag="0" />
<vel value="26.36429800" flag="0" />
<psa03 value="71.37681307" flag="0" />
<psa10 value="20.06593206" flag="0" />
<psa30 value="5.68875022" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="44.97555708" flag="0" />
<vel value="29.70794300" flag="0" />
<psa03 value="136.45416643" flag="0" />
<psa10 value="20.87029235" flag="0" />
<psa30 value="3.22763860" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="36.15417317" flag="0" />
<vel value="22.88884900" flag="0" />
<psa03 value="77.57729780" flag="0" />
<psa10 value="18.74136783" flag="0" />
<psa30 value="5.94625763" flag="0" />
</comp>
</station>
<station code="ANB" name="Ancona2" insttype="UNR" lat="43.5922" lon="13.5074" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="4.19164756" flag="0" />
<vel value="2.78396700" flag="0" />
<psa03 value="10.94598945" flag="0" />
<psa10 value="3.62764235" flag="0" />
<psa30 value="0.63690386" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="5.32985959" flag="0" />
<vel value="2.79328200" flag="0" />
<psa03 value="16.46367363" flag="0" />
<psa10 value="3.26263760" flag="0" />
<psa30 value="0.50369147" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="2.32533912" flag="0" />
<vel value="1.51054700" flag="0" />
<psa03 value="7.61302905" flag="0" />
<psa10 value="1.18565439" flag="0" />
<psa30 value="0.30544913" flag="0" />
</comp>
</station>
<station code="ANT" name="Antrodoco" insttype="UNR" lat="42.4182" lon="13.0786" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="3.95399618" flag="0" />
<vel value="5.54060600" flag="0" />
<psa03 value="8.38405304" flag="0" />
<psa10 value="5.50580200" flag="0" />
<psa30 value="0.91223158" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="4.68477002" flag="0" />
<vel value="5.26984100" flag="0" />
<psa03 value="10.19158217" flag="0" />
<psa10 value="7.31653581" flag="0" />
<psa30 value="1.32798741" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="1.88072906" flag="0" />
<vel value="2.54164100" flag="0" />
<psa03 value="5.18509247" flag="0" />
<psa10 value="4.03169843" flag="0" />
<psa30 value="1.21033089" flag="0" />
</comp>
</station>
<station code="AQA" name="L_Aquila_Fiume_Aterno" insttype="UNR" lat="42.3755" lon="13.3393" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="3.66926984" flag="0" />
<vel value="3.49780900" flag="0" />
<psa03 value="5.89428127" flag="0" />
<psa10 value="6.13355671" flag="0" />
<psa30 value="1.13067447" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="3.71399205" flag="0" />
<vel value="4.95543200" flag="0" />
<psa03 value="10.32490564" flag="0" />
<psa10 value="5.02144053" flag="0" />
<psa30 value="1.77502544" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="2.12616205" flag="0" />
<vel value="3.49320700" flag="0" />
<psa03 value="3.50974647" flag="0" />
<psa10 value="4.35536736" flag="0" />
<psa30 value="2.15271106" flag="0" />
</comp>
</station>
<station code="AQF" name="L_Aquila_Valle_Aterno_Ferriera" insttype="UNR" lat="42.3807" lon="13.3547" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="4.63691794" flag="0" />
<vel value="3.26181600" flag="0" />
<psa03 value="10.28770658" flag="0" />
<psa10 value="3.91716166" flag="0" />
<psa30 value="0.95057293" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="5.25790895" flag="0" />
<vel value="4.70077400" flag="0" />
<psa03 value="21.40321660" flag="0" />
<psa10 value="3.46547721" flag="0" />
<psa30 value="2.99189069" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="5.17334867" flag="0" />
<vel value="3.55529000" flag="0" />
<psa03 value="15.85878546" flag="0" />
<psa10 value="3.33495453" flag="0" />
<psa30 value="2.52637317" flag="0" />
</comp>
</station>
<station code="AQG" name="L_Aquila_Colle_dei_Grilli" insttype="UNR" lat="42.3737" lon="13.3370" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="5.35344469" flag="0" />
<vel value="4.99278100" flag="0" />
<psa03 value="9.51927050" flag="0" />
<psa10 value="4.93058708" flag="0" />
<psa30 value="1.25898872" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="8.79175980" flag="0" />
<vel value="6.32853600" flag="0" />
<psa03 value="14.89350104" flag="0" />
<psa10 value="7.62764345" flag="0" />
<psa30 value="1.86804195" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="2.14773044" flag="0" />
<vel value="4.82814500" flag="0" />
<psa03 value="3.75821297" flag="0" />
<psa10 value="3.91050599" flag="0" />
<psa30 value="2.19770154" flag="0" />
</comp>
</station>
<station code="AQK" name="L_Aquila_Aquilpark" insttype="UNR" lat="42.3450" lon="13.4009" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="5.70909671" flag="0" />
<vel value="13.71009900" flag="0" />
<psa03 value="9.68601215" flag="0" />
<psa10 value="11.45305342" flag="0" />
<psa30 value="3.14481429" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="7.34815680" flag="0" />
<vel value="14.44539500" flag="0" />
<psa03 value="13.28575360" flag="0" />
<psa10 value="17.59355779" flag="0" />
<psa30 value="3.42104035" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="3.57761831" flag="0" />
<vel value="5.25176100" flag="0" />
<psa03 value="7.43935334" flag="0" />
<psa10 value="6.28894323" flag="0" />
<psa30 value="1.13412229" flag="0" />
</comp>
</station>
<station code="AQV" name="L_Aquila_Centro_Valle" insttype="UNR" lat="42.3771" lon="13.3439" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="6.86779370" flag="0" />
<vel value="4.62201200" flag="0" />
<psa03 value="13.23218966" flag="0" />
<psa10 value="6.63434897" flag="0" />
<psa30 value="1.19198946" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="7.08812270" flag="0" />
<vel value="4.84285400" flag="0" />
<psa03 value="16.07502952" flag="0" />
<psa10 value="5.81269521" flag="0" />
<psa30 value="2.17508427" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="2.66019374" flag="0" />
<vel value="4.04145100" flag="0" />
<psa03 value="7.09875426" flag="0" />
<psa10 value="4.89644881" flag="0" />
<psa30 value="2.28680594" flag="0" />
</comp>
</station>
<station code="ASP" name="Ascoli_Piceno" insttype="UNR" lat="42.8480" lon="13.6479" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="13.99954895" flag="0" />
<vel value="6.82748200" flag="0" />
<psa03 value="16.19248563" flag="0" />
<psa10 value="3.53885201" flag="0" />
<psa30 value="2.38037822" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="11.88866263" flag="0" />
<vel value="7.57882100" flag="0" />
<psa03 value="24.23527600" flag="0" />
<psa10 value="3.36197825" flag="0" />
<psa30 value="2.48156072" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="5.58302473" flag="0" />
<vel value="5.19114600" flag="0" />
<psa03 value="7.96812009" flag="0" />
<psa10 value="5.40263672" flag="0" />
<psa30 value="1.85780867" flag="0" />
</comp>
</station>
<station code="AVZ" name="Avezzano" insttype="UNR" lat="42.0274" lon="13.4259" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="1.88268721" flag="0" />
<vel value="3.36663400" flag="0" />
<psa03 value="4.44202397" flag="0" />
<psa10 value="4.97959188" flag="0" />
<psa30 value="2.21686404" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="1.72385850" flag="0" />
<vel value="3.40417400" flag="0" />
<psa03 value="4.35699469" flag="0" />
<psa10 value="4.01687391" flag="0" />
<psa30 value="1.16203761" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="1.03743475" flag="0" />
<vel value="1.74052400" flag="0" />
<psa03 value="3.00118139" flag="0" />
<psa10 value="1.59843600" flag="0" />
<psa30 value="1.09378671" flag="0" />
</comp>
</station>
<station code="BDT" name="Badia_Tedalda" insttype="UNR" lat="43.7068" lon="12.1880" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="1.02346320" flag="0" />
<vel value="1.63295000" flag="0" />
<psa03 value="2.37588683" flag="0" />
<psa10 value="1.54387755" flag="0" />
<psa30 value="0.77319829" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="1.04415492" flag="0" />
<vel value="1.46602400" flag="0" />
<psa03 value="2.67111065" flag="0" />
<psa10 value="2.65901517" flag="0" />
<psa30 value="0.64802230" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.49894101" flag="0" />
<vel value="1.09267300" flag="0" />
<psa03 value="1.11514048" flag="0" />
<psa10 value="1.08296864" flag="0" />
<psa30 value="0.92142743" flag="0" />
</comp>
</station>
<station code="BGR" name="Bagno_di_Romagna" insttype="UNR" lat="43.8895" lon="11.9912" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="0.32489492" flag="0" />
<vel value="0.82468700" flag="0" />
<psa03 value="0.76816290" flag="0" />
<psa10 value="0.85264366" flag="0" />
<psa30 value="0.55957770" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="0.27719420" flag="0" />
<vel value="0.64989400" flag="0" />
<psa03 value="0.91111525" flag="0" />
<psa10 value="0.70411743" flag="0" />
<psa30 value="0.30744530" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.28529682" flag="0" />
<vel value="0.61924400" flag="0" />
<psa03 value="0.52934909" flag="0" />
<psa10 value="0.72877614" flag="0" />
<psa30 value="0.27051665" flag="0" />
</comp>
</station>
<station code="BRS" name="Barisciano" insttype="UNR" lat="42.3243" lon="13.5902" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="6.01856812" flag="0" />
<vel value="2.11204700" flag="0" />
<psa03 value="8.18194773" flag="0" />
<psa10 value="1.78614909" flag="0" />
<psa30 value="0.87856404" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="6.00672406" flag="0" />
<vel value="2.89856900" flag="0" />
<psa03 value="7.86526979" flag="0" />
<psa10 value="1.67514610" flag="0" />
<psa30 value="1.53691354" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="4.20560307" flag="0" />
<vel value="2.46510400" flag="0" />
<psa03 value="3.08863965" flag="0" />
<psa10 value="1.84017794" flag="0" />
<psa30 value="1.36810183" flag="0" />
</comp>
</station>
<station code="BSS" name="Bussi" insttype="UNR" lat="42.1917" lon="13.8453" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="1.49458200" flag="0" />
<vel value="1.65163200" flag="0" />
<psa03 value="4.52201591" flag="0" />
<psa10 value="2.46572370" flag="0" />
<psa30 value="0.49583056" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="1.85691748" flag="0" />
<vel value="2.20412300" flag="0" />
<psa03 value="4.04832688" flag="0" />
<psa10 value="3.44724177" flag="0" />
<psa30 value="0.71273503" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.93550047" flag="0" />
<vel value="1.54567000" flag="0" />
<psa03 value="2.52616499" flag="0" />
<psa10 value="1.19396836" flag="0" />
<psa30 value="0.89580600" flag="0" />
</comp>
</station>
<station code="BTT2" name="Borgo_Ottomila_2" insttype="UNR" lat="41.9983" lon="13.5431" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="3.48635514" flag="0" />
<vel value="11.67618000" flag="0" />
<psa03 value="6.73791191" flag="0" />
<psa10 value="8.36766629" flag="0" />
<psa30 value="8.61068368" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="4.09582729" flag="0" />
<vel value="17.12053700" flag="0" />
<psa03 value="6.49980952" flag="0" />
<psa10 value="10.57359861" flag="0" />
<psa30 value="16.09360876" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="1.38712319" flag="0" />
<vel value="4.21245200" flag="0" />
<psa03 value="2.51693581" flag="0" />
<psa10 value="2.94934493" flag="0" />
<psa30 value="2.62880301" flag="0" />
</comp>
</station>
<station code="BVG" name="Bevagna" insttype="UNR" lat="42.9323" lon="12.6110" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="7.65674347" flag="0" />
<vel value="11.47588800" flag="0" />
<psa03 value="12.62296084" flag="0" />
<psa10 value="10.17618890" flag="0" />
<psa30 value="5.94132781" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="8.39891608" flag="0" />
<vel value="7.25949900" flag="0" />
<psa03 value="11.27942523" flag="0" />
<psa10 value="10.43091535" flag="0" />
<psa30 value="3.34898679" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="4.34369612" flag="0" />
<vel value="3.95004200" flag="0" />
<psa03 value="11.76832622" flag="0" />
<psa10 value="4.87400559" flag="0" />
<psa30 value="1.41595933" flag="0" />
</comp>
</station>
<station code="BZZ" name="L_Aquila_Bazzano" insttype="UNR" lat="42.3370" lon="13.4685" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="3.58543467" flag="0" />
<vel value="3.51983800" flag="0" />
<psa03 value="9.78069565" flag="0" />
<psa10 value="3.69448963" flag="0" />
<psa30 value="1.99582435" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="3.54990065" flag="0" />
<vel value="2.91613300" flag="0" />
<psa03 value="9.19443199" flag="0" />
<psa10 value="3.65710569" flag="0" />
<psa30 value="1.48859451" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="3.52514014" flag="0" />
<vel value="4.27081900" flag="0" />
<psa03 value="4.28720354" flag="0" />
<psa10 value="2.87324733" flag="0" />
<psa30 value="2.31446760" flag="0" />
</comp>
</station>
<station code="CCT" name="Citta_di_Castello_(Trestina)" insttype="UNR" lat="43.3683" lon="12.2346" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="2.07451610" flag="0" />
<vel value="2.56872800" flag="0" />
<psa03 value="4.59538243" flag="0" />
<psa10 value="3.72882863" flag="0" />
<psa30 value="0.94904208" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="2.16904977" flag="0" />
<vel value="2.11517000" flag="0" />
<psa03 value="4.10903225" flag="0" />
<psa10 value="3.69033173" flag="0" />
<psa30 value="1.07984081" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="1.11442907" flag="0" />
<vel value="1.59022400" flag="0" />
<psa03 value="2.19555013" flag="0" />
<psa10 value="2.41295508" flag="0" />
<psa30 value="0.41158996" flag="0" />
</comp>
</station>
<station code="CDM" name="Colle_di_Macine" insttype="UNR" lat="42.0033" lon="14.1994" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="0.91165916" flag="0" />
<vel value="1.91035200" flag="0" />
<psa03 value="1.47646511" flag="0" />
<psa10 value="1.97858096" flag="0" />
<psa30 value="1.16803409" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="0.85285491" flag="0" />
<vel value="2.34659700" flag="0" />
<psa03 value="1.21531202" flag="0" />
<psa10 value="1.95783211" flag="0" />
<psa30 value="0.79031638" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.72183318" flag="0" />
<vel value="1.80326400" flag="0" />
<psa03 value="1.14338611" flag="0" />
<psa10 value="1.48566658" flag="0" />
<psa30 value="0.63941185" flag="0" />
</comp>
</station>
<station code="CIT" name="Cittareale" insttype="UNR" lat="42.5942" lon="13.1632" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="35.95745187" flag="0" />
<vel value="15.25236800" flag="0" />
<psa03 value="65.83008651" flag="0" />
<psa10 value="18.70502183" flag="0" />
<psa30 value="2.85258913" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="24.67882053" flag="0" />
<vel value="14.26750800" flag="0" />
<psa03 value="85.79482902" flag="0" />
<psa10 value="10.82457544" flag="0" />
<psa30 value="4.10313480" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="13.53813936" flag="0" />
<vel value="8.68684000" flag="0" />
<psa03 value="20.85376212" flag="0" />
<psa10 value="8.70398789" flag="0" />
<psa30 value="3.89299065" flag="0" />
</comp>
</station>
<station code="CLF" name="Colfiorito_Casone" insttype="UNR" lat="43.0367" lon="12.9204" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="11.70040522" flag="0" />
<vel value="9.57094100" flag="0" />
<psa03 value="37.39514464" flag="0" />
<psa10 value="24.37690507" flag="0" />
<psa30 value="1.61267757" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="16.59169968" flag="0" />
<vel value="10.91405800" flag="0" />
<psa03 value="60.61598396" flag="0" />
<psa10 value="19.83351188" flag="0" />
<psa30 value="2.23689494" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="9.77126484" flag="0" />
<vel value="5.14775400" flag="0" />
<psa03 value="38.82258870" flag="0" />
<psa10 value="8.22519980" flag="0" />
<psa30 value="1.47317559" flag="0" />
</comp>
</station>
<station code="CLN" name="Celano" insttype="UNR" lat="42.0852" lon="13.5207" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="0.73599606" flag="0" />
<vel value="1.09584800" flag="0" />
<psa03 value="1.49878773" flag="0" />
<psa10 value="1.05466833" flag="0" />
<psa30 value="0.61226456" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="0.71350777" flag="0" />
<vel value="1.83892200" flag="0" />
<psa03 value="1.99893256" flag="0" />
<psa10 value="0.67654734" flag="0" />
<psa30 value="1.34157593" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.43658869" flag="0" />
<vel value="1.28787900" flag="0" />
<psa03 value="0.98063159" flag="0" />
<psa10 value="0.55428875" flag="0" />
<psa30 value="1.00609799" flag="0" />
</comp>
</station>
<station code="CLO" name="Castelluccio" insttype="UNR" lat="42.8294" lon="13.2060" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="48.89782833" flag="0" />
<vel value="66.09681700" flag="0" />
<psa03 value="115.08679372" flag="0" />
<psa10 value="88.09778481" flag="0" />
<psa30 value="10.45316327" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="64.79431343" flag="0" />
<vel value="54.36327700" flag="0" />
<psa03 value="160.27168174" flag="0" />
<psa10 value="103.98289842" flag="0" />
<psa30 value="8.36240861" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="66.40377630" flag="0" />
<vel value="53.98617200" flag="0" />
<psa03 value="148.43843880" flag="0" />
<psa10 value="62.09124699" flag="0" />
<psa30 value="19.13488065" flag="0" />
</comp>
</station>
<station code="CMB" name="Campobasso" insttype="UNR" lat="41.5628" lon="14.6524" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="0.18715099" flag="0" />
<vel value="0.81180300" flag="0" />
<psa03 value="0.20814144" flag="0" />
<psa10 value="0.32174400" flag="0" />
<psa30 value="0.41602053" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="0.24058555" flag="0" />
<vel value="1.01660400" flag="0" />
<psa03 value="0.25397640" flag="0" />
<psa10 value="0.36727450" flag="0" />
<psa30 value="0.66223689" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.20025436" flag="0" />
<vel value="0.96588500" flag="0" />
<psa03 value="0.21693432" flag="0" />
<psa10 value="0.39164512" flag="0" />
<psa30 value="0.42749381" flag="0" />
</comp>
</station>
<station code="CNE" name="Castel Santangelo sul Nera" insttype="UNR" lat="42.8944" lon="13.1528" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="46.46586558" flag="0" />
<vel value="39.53915000" flag="0" />
<psa03 value="108.76648725" flag="0" />
<psa10 value="52.75483661" flag="0" />
<psa30 value="4.05277248" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="35.07976951" flag="0" />
<vel value="27.87291500" flag="0" />
<psa03 value="71.47374221" flag="0" />
<psa10 value="31.48959532" flag="0" />
<psa30 value="2.53960786" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="60.89750806" flag="0" />
<vel value="16.83345600" flag="0" />
<psa03 value="100.74234634" flag="0" />
<psa10 value="19.05133471" flag="0" />
<psa30 value="2.84009906" flag="0" />
</comp>
</station>
<station code="CPS" name="Capestrano" insttype="UNR" lat="42.2716" lon="13.7583" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="1.91481624" flag="0" />
<vel value="1.75677100" flag="0" />
<psa03 value="4.41797539" flag="0" />
<psa10 value="2.22553071" flag="0" />
<psa30 value="0.70812653" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="1.91899673" flag="0" />
<vel value="2.02115800" flag="0" />
<psa03 value="5.81889006" flag="0" />
<psa10 value="2.07913902" flag="0" />
<psa30 value="1.06591238" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="1.21278021" flag="0" />
<vel value="1.80864200" flag="0" />
<psa03 value="3.13183928" flag="0" />
<psa10 value="1.50773688" flag="0" />
<psa30 value="1.32957264" flag="0" />
</comp>
</station>
<station code="CRO" name="Cortona" insttype="UNR" lat="43.2678" lon="11.9805" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="0.29428286" flag="0" />
<vel value="0.77282300" flag="0" />
<psa03 value="0.78102242" flag="0" />
<psa10 value="0.47967366" flag="0" />
<psa30 value="0.32588167" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="0.36176204" flag="0" />
<vel value="0.41636000" flag="0" />
<psa03 value="1.04894503" flag="0" />
<psa10 value="0.56309512" flag="0" />
<psa30 value="0.14376505" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="0.23247894" flag="0" />
<vel value="0.48868100" flag="0" />
<psa03 value="0.50535519" flag="0" />
<psa10 value="0.41758389" flag="0" />
<psa30 value="0.21366239" flag="0" />
</comp>
</station>
<station code="CSA" name="Castelnuovo_Assisi" insttype="UNR" lat="43.0080" lon="12.5906" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="6.42376148" flag="0" />
<vel value="9.70753700" flag="0" />
<psa03 value="18.03199825" flag="0" />
<psa10 value="8.91732742" flag="0" />
<psa30 value="7.01721767" flag="0" />
</comp>
<comp name="--.HGN">
<acc value="6.70564226" flag="0" />
<vel value="15.25659400" flag="0" />
<psa03 value="15.37574329" flag="0" />
<psa10 value="8.86123015" flag="0" />
<psa30 value="8.42820875" flag="0" />
</comp>
<comp name="--.HGZ">
<acc value="2.74283961" flag="0" />
<vel value="5.39572600" flag="0" />
<psa03 value="7.58993441" flag="0" />
<psa10 value="4.68208073" flag="0" />
<psa30 value="3.28926735" flag="0" />
</comp>
</station>
<station code="CSC" name="Cascia" insttype="UNR" lat="42.7190" lon="13.0122" netid="IT" source="DPC, Dipartimento Protezione Civile" commtype="DIG">
<comp name="--.HGE">
<acc value="15.40554900" flag="0" />
<vel value="10.99188300" flag="0" />
<psa03 value="33.83205498" flag="0" />